version: "3"

services:
  db:
    container_name: laravel_mariadb
    build: ./db/
    image: laravel_mariadb
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci  --default-time-zone=Asia/Tokyo
    restart: always
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: laravel
      MYSQL_PASSWORD: passwrord
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    networks:
      - app_net
  app:
    container_name: laravel
    build: ./app/
    image: laravel
    restart: always
    ports:
      - 80:80
    links:
      - db
    volumes:
      - ../project:/work/surveycloud
    stdin_open: true
    tty: true
    # privileged: true
    environment: 
      TZ: Asia/Tokyo
    depends_on:
      - db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge