version: "3"

services:
  db:
    container_name: laravel_mariadb
    build: ./db/
    image: laravel_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${ENV_DB_DATABASE}
      MYSQL_USER: ${ENV_DB_USERNAME}
      MYSQL_PASSWORD: ${ENV_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ENV_DB_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - ${ENV_DB_PORT}:3306
    networks:
      - app_net
  app:
    container_name: laravel
    build:
      context: ./app/
      args:
        ENV_DB_CONNECTION: ${ENV_DB_CONNECTION}
        ENV_DB_HOST: ${ENV_DB_HOST}
        ENV_DB_PORT: ${ENV_DB_PORT}
        ENV_DB_DATABASE: ${ENV_DB_DATABASE}
        ENV_DB_USERNAME: ${ENV_DB_USERNAME}
        ENV_DB_PASSWORD: ${ENV_DB_PASSWORD}
        ENV_DB_ROOT_PASSWORD: ${ENV_DB_ROOT_PASSWORD}
        ENV_DOUCMENT_ROOT: ${ENV_DOUCMENT_ROOT}
        ENV_SRC_DIRECTORY: ${ENV_SRC_DIRECTORY}
    image: laravel
    restart: always
    env_file: 
      - ./.env
    ports:
      - ${ENV_APP_PORT}:80
    links:
      - db
    volumes:
      - ../project/${ENV_SRC_DIRECTORY}:${ENV_DOUCMENT_ROOT}/${ENV_SRC_DIRECTORY}
    stdin_open: true
    tty: true
    # privileged: true
    environment: 
      TZ: Asia/Tokyo
    depends_on:
      - db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge